version: "3.9"

services:
  argilla:
    image: argilla/argilla-server:latest
    restart: unless-stopped
    ports:
      - "80:6900"
    environment:
      ARGILLA_HOME_PATH: /var/lib/argilla
      ARGILA_SEARCH_ENGINE: opensearch
      ARGILLA_ELASTICSEARCH: https://zmm5gdfb80vif4j6jwp2.ap-southeast-1.aoss.amazonaws.com
      ARGILLA_AUTH_SECRET_KEY: ${ARGILLA_SECRET:? Please generate a 32 character random string with `openssl rand -hex 32`}
      ARGILLA_ENABLE_TELEMETRY: 0 # Opt-out for telemetry https://docs.argilla.io/en/latest/reference/telemetry.html
      ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /config/.users.yaml
      # DEFAULT_USER_ENABLED: false # Uncomment this line to disable the creation of the default user
      DEFAULT_USER_PASSWORD: ${DEFAULT_PASSWORD} # Uncomment this line to set a custom password for the default user
      DEFAULT_USER_API_KEY: ${DEFAULT_APIKEY} # Uncomment this line to set a custom api-key for the default user
    volumes:
      - argilladata:/var/lib/argilla
      - ${PWD}/.users.yaml:/config/.users.yaml

volumes:
  argilladata:
