version: "3.9"

services:

  argilla:
    image: argilla/argilla-server:latest
    restart: unless-stopped
    ports:
      - "6900:6900"
    environment:
      ARGILLA_HOME_PATH: /mnt/efs/fs1/argilla/data
      ARGILLA_ELASTICSEARCH: http://elasticsearch:9200
      ARGILLA_AUTH_SECRET_KEY: ${ARGILLA_SECRET:? Please generate a 32 character random string with `openssl rand -hex 32`}
      ARGILLA_ENABLE_TELEMETRY: 0
      ARGILLA_LOCAL_AUTH_USERS_DB_FILE: /mnt/efs/fs1/argilla/config/.users.yaml
    volumes:
      - /mnt/efs/fs1/argilla/data:/var/lib/argilla
      - /mnt/efs/fs1/argilla/config/.users.yaml:/config/.users.yaml
    networks:
      - argilla
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - node.name=elasticsearch
      - cluster.name=es-argilla-local
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mnt/efs/fs1/elasticsearch:/usr/share/elasticsearch/data/
    networks:
      - argilla
    ports:
      - "9200:9200"
      - "9300:9300"
      
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
      - argilla

networks:
  argilla:
    driver: bridge
